# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import lidar_pb2 as lidar__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lidar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LidarScanSourceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeScans = channel.unary_stream(
                '/ajin.edge.lidar.v1.LidarScanSource/SubscribeScans',
                request_serializer=lidar__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=lidar__pb2.ScanFrame.FromString,
                _registered_method=True)


class LidarScanSourceServicer:
    """Missing associated documentation comment in .proto file."""

    def SubscribeScans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LidarScanSourceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeScans': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeScans,
                    request_deserializer=lidar__pb2.SubscribeRequest.FromString,
                    response_serializer=lidar__pb2.ScanFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ajin.edge.lidar.v1.LidarScanSource', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ajin.edge.lidar.v1.LidarScanSource', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LidarScanSource:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeScans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ajin.edge.lidar.v1.LidarScanSource/SubscribeScans',
            lidar__pb2.SubscribeRequest.SerializeToString,
            lidar__pb2.ScanFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
